# screen size
WINDOW_WIDTH = 500
WINDOW_HEIGHT = 650

# ball parameters
RADIUS = 20
X_POS_START = 240
Y_POS_START = 550

# change color ball parameters
CHANGE_COLOR_BALL_RADIUS = 12

# players movement parameters
X_POS_LEFTEST = 110
X_POS_RIGHTEST = 390
X_POS_CHANGE_LEFT = -5
X_POS_CHANGE_RIGHT = 5

CANT_MOVE_LOOP_TIMES = 0
START_MOVE_RIGHT_LOOP_TIMES = 30
START_MOVE_LEFT_LOOP_TIMES = 26
MOVE_LOOP_TIMES = 56

# block parameters
BLOCK_WIDTH = 20
BLOCK_START_HEIGHT = 250
BLOCK_HEIGHT_LIST = [300, 250, 200, 150, 100, 50]

# block movement parameters
X_POS_RIGHT_BLOCK = 419
Y_POS_BLOCK = 340
Y_POS_BLOCK2 = 90
Y_POS_BLOCK3 = -160
X_POS_LEFT_BLOCK = 79
Y_POS_CHANGE = 5

# game over img
GAME_OVER = "./images/gameOver.png"
GAME_OVER_WIDTH = 400
GAME_OVER_HEIGHT = 300
GAME_OVER_X_POS = 50
GAME_OVER_Y_POS = 0

# home button img
HOME_BUTTON = "./images/home.png"
HOME_BUTTON_WIDTH = 50
HOME_BUTTON_HEIGHT = 60
HOME_BUTTON_X_POS = 20
HOME_BUTTON_Y_POS = 20

# background img
BACKGROUND = "./images/blackBackground.png"
BACKGROUND_WIDTH = 500
BACKGROUND_HEIGHT = 650
BACKGROUND_X_POS = 0
BACKGROUND_Y_POS = 0

#garfeild img
GARFIELD = "images/howToPlay.png"
GARFIELD_WIDTH = 400
GARFIELD_HEIGHT = 400
GARFIELD_X_POS = 100
GARFIELD_Y_POS = 50

# score parameters
X_POS_SCORE = 120
Y_POS_SCORE = 50
SCORE_FONT = "Arial"
SCORE_FONT_SIZE = 20
SCORE_CHANGE = 10
X_START_SCORE_REC = 170
Y_START_SCORE_REC = 50
Y_END_SCORE_REC = 80
SCORE_REC_WIDTH = 120

GAME_OVER_X_POS_SCORE = 200
GAME_OVER_Y_POS_SCORE = 400
GAME_OVER_X_POS_HIGH_SCORE = 200
GAME_OVER_Y_POS_HIGH_SCORE = 430

# text file
HS_FILE = "highscore.txt"

# colors
BLACK = (0, 0, 0)
RED = (255, 0, 0)
YELLOW = (255, 255, 0)
WHITE = (255, 255, 255)

# animation parameters
AMOUNT_OF_LOADING_SCREENS = 12
LOADING_SCREEN_IMAGE_PATH = "images/animation/rollColor_"
LOADING_SCREEN_PATH_EXTENSION = ".png"
IMG_HEIGHT = 350
IMG_X = 0
IMG_Y = 150

# sounds
GAME_OVER_SOUND = "sounds/Game Over (8-Bit Music).mp3"
POP_SOUND = "sounds/POP - Sound Effect.mp3"
ANIMATION_SOUND = "sounds/ani.mp3"

# best score parameters
BEST_SCORE_SIZE = 22
BEST_SCORE_WIDTH = 250
BEST_SCORE_HEIGHT = 365
NEW_BEST_SCORE_HEIGHT = 30

GAME_OVER_BEST_SCORE_X = 170
GAME_OVER_BEST_SCORE_Y = 450